# Merging the count data

In [1]:
import pandas as pd
strain_nums = [1, 3, 6, 7, 14, 17, 43, 54, 56, 57, 66, 68, 86 ]
media = ['UR', 'UTI']
filenames = []
for strain in strain_nums:
    for m in media:
        s = m + str(strain)
        filenames.append(s)
filenames.remove("UR1")
print (filenames)

['UTI1', 'UR3', 'UTI3', 'UR6', 'UTI6', 'UR7', 'UTI7', 'UR14', 'UTI14', 'UR17', 'UTI17', 'UR43', 'UTI43', 'UR54', 'UTI54', 'UR56', 'UTI56', 'UR57', 'UTI57', 'UR66', 'UTI66', 'UR68', 'UTI68', 'UR86', 'UTI86']

In [4]:
comb = pd.read_table("UR1", sep = "\t", header = None)
comb.columns = ["Gene_id", 'UR1']
comb = comb.set_index("Gene_id")

In [5]:
for name in filenames:
    x = pd.read_table(name, sep = "\t", header = None)
    x.columns = ["Gene_id", name]
    x = x.set_index("Gene_id")
    comb = pd.merge(comb, x, how='outer', left_index=True, right_index=True)
print (comb.head())

                                          UR1  UTI1  UR3  UTI3     UR6   UTI6  \
Gene_id
10002_aldA_2                              NaN   NaN  NaN   NaN   650.0   29.0
10011_ydbC_2                              NaN   NaN  NaN   NaN   110.0    4.0
10012_putative_autotransporter_precursor  NaN   NaN  NaN   NaN  4668.0  121.0
10013_hypothetical_protein                NaN   NaN  NaN   NaN     NaN    NaN
10023_mntB_1                              NaN   NaN  NaN   NaN    39.0    2.0

                                          UR7  UTI7  UR14  UTI14  ...    UR56  \
Gene_id                                                           ...
10002_aldA_2                              NaN   NaN   NaN    NaN  ...     NaN
10011_ydbC_2                              NaN   NaN   NaN    NaN  ...     NaN
10012_putative_autotransporter_precursor  NaN   NaN   NaN    NaN  ...     NaN
10013_hypothetical_protein                NaN   NaN   NaN    NaN  ...     NaN
10023_mntB_1                              NaN   NaN   NaN    NaN  ...    52.0

                                          UTI56  UR57  UTI57    UR66  UTI66  \
Gene_id
10002_aldA_2                                NaN   NaN    NaN     NaN    NaN
10011_ydbC_2                                NaN   NaN    NaN     NaN    NaN
10012_putative_autotransporter_precursor    NaN   NaN    NaN  1377.0    7.0
10013_hypothetical_protein                  NaN   NaN    NaN     NaN    NaN
10023_mntB_1                               19.0  38.0    1.0    81.0    0.0

                                            UR68  UTI68    UR86  UTI86
Gene_id
10002_aldA_2                              1181.0    7.0   298.0   52.0
10011_ydbC_2                                28.0    1.0     NaN    NaN
10012_putative_autotransporter_precursor  2885.0   39.0  1887.0  424.0
10013_hypothetical_protein                   NaN    NaN     NaN    NaN
10023_mntB_1                                 NaN    NaN    21.0   10.0

[5 rows x 26 columns]

In [6]:
comb.tail(10)

,UR1,UTI1,UR3,UTI3,UR6,UTI6,UR7,UTI7,UR14,UTI14,...,UR56,UTI56,UR57,UTI57,UR66,UTI66,UR68,UTI68,UR86,UTI86
Gene_id,,,,,,,,,,,,,,,,,,,,,
9986_ydcO_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987_ydcO_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997_trg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,191.0,5.0,208.0,0.0,265.0,5.0,NaN,NaN
99_hypothetical_protein,83.0,4.0,NaN,NaN,57.0,0.0,NaN,NaN,NaN,NaN,...,35.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9_Phage_major_capsid_protein_E,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
__alignment_not_unique,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
__ambiguous,227176.0,78960.0,314434.0,171333.0,404507.0,26260.0,345243.0,14515.0,331154.0,319503.0,...,270444.0,299266.0,278903.0,5343.0,324260.0,1240.0,249147.0,14336.0,243435.0,126461.0
__no_feature,3100135.0,535449.0,3816096.0,1204805.0,3875867.0,272764.0,4283357.0,137358.0,3763749.0,1778642.0,...,3119846.0,2339832.0,3559097.0,64715.0,3665237.0,21799.0,2433062.0,149601.0,2781047.0,1033372.0
__not_aligned,764480.0,14775419.0,414293.0,8481744.0,507365.0,17317571.0,327720.0,22188812.0,388930.0,2975377.0,...,360838.0,10447704.0,283418.0,33529597.0,445554.0,25873688.0,273355.0,19467559.0,406857.0,4252392.0
__too_low_aQual,807094.0,112746.0,522423.0,221155.0,582171.0,54467.0,574902.0,27633.0,1073691.0,429999.0,...,394927.0,437142.0,512726.0,15387.0,337030.0,4588.0,693935.0,36813.0,472033.0,230186.0

In [7]:
df = comb.copy()

In [8]:
df.tail(10)

,UR1,UTI1,UR3,UTI3,UR6,UTI6,UR7,UTI7,UR14,UTI14,...,UR56,UTI56,UR57,UTI57,UR66,UTI66,UR68,UTI68,UR86,UTI86
Gene_id,,,,,,,,,,,,,,,,,,,,,
9986_ydcO_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987_ydcO_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997_trg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,191.0,5.0,208.0,0.0,265.0,5.0,NaN,NaN
99_hypothetical_protein,83.0,4.0,NaN,NaN,57.0,0.0,NaN,NaN,NaN,NaN,...,35.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9_Phage_major_capsid_protein_E,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
__alignment_not_unique,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
__ambiguous,227176.0,78960.0,314434.0,171333.0,404507.0,26260.0,345243.0,14515.0,331154.0,319503.0,...,270444.0,299266.0,278903.0,5343.0,324260.0,1240.0,249147.0,14336.0,243435.0,126461.0
__no_feature,3100135.0,535449.0,3816096.0,1204805.0,3875867.0,272764.0,4283357.0,137358.0,3763749.0,1778642.0,...,3119846.0,2339832.0,3559097.0,64715.0,3665237.0,21799.0,2433062.0,149601.0,2781047.0,1033372.0
__not_aligned,764480.0,14775419.0,414293.0,8481744.0,507365.0,17317571.0,327720.0,22188812.0,388930.0,2975377.0,...,360838.0,10447704.0,283418.0,33529597.0,445554.0,25873688.0,273355.0,19467559.0,406857.0,4252392.0
__too_low_aQual,807094.0,112746.0,522423.0,221155.0,582171.0,54467.0,574902.0,27633.0,1073691.0,429999.0,...,394927.0,437142.0,512726.0,15387.0,337030.0,4588.0,693935.0,36813.0,472033.0,230186.0

In [9]:
comb = comb.drop(["__alignment_not_unique", "__ambiguous", "__no_feature", "__not_aligned", "__too_low_aQual"])

In [10]:
comb.tail()

,UR1,UTI1,UR3,UTI3,UR6,UTI6,UR7,UTI7,UR14,UTI14,...,UR56,UTI56,UR57,UTI57,UR66,UTI66,UR68,UTI68,UR86,UTI86
Gene_id,,,,,,,,,,,,,,,,,,,,,
9986_ydcO_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987_ydcO_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997_trg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,191.0,5.0,208.0,0.0,265.0,5.0,NaN,NaN
99_hypothetical_protein,83.0,4.0,NaN,NaN,57.0,0.0,NaN,NaN,NaN,NaN,...,35.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9_Phage_major_capsid_protein_E,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
comb.to_csv("2017-02-01-combined_counts.csv")

In [13]:
df = pd.read_csv("2017-02-01-combined_counts.csv")

In [14]:
df.head()

,Gene_id,UR1,UTI1,UR3,UTI3,UR6,UTI6,UR7,UTI7,UR14,...,UR56,UTI56,UR57,UTI57,UR66,UTI66,UR68,UTI68,UR86,UTI86
0,10002_aldA_2,NaN,NaN,NaN,NaN,650.0,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1181.0,7.0,298.0,52.0
1,10011_ydbC_2,NaN,NaN,NaN,NaN,110.0,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1.0,NaN,NaN
2,10012_putative_autotransporter_precursor,NaN,NaN,NaN,NaN,4668.0,121.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1377.0,7.0,2885.0,39.0,1887.0,424.0
3,10013_hypothetical_protein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10023_mntB_1,NaN,NaN,NaN,NaN,39.0,2.0,NaN,NaN,NaN,...,52.0,19.0,38.0,1.0,81.0,0.0,NaN,NaN,21.0,10.0