In [24]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os
import seaborn as sns; sns.set(color_codes=True)

fimbriae_data = "/Users/annasintsova/git_repos/HUTI-RNAseq/analysis/comparative-genomics-huti/data/fimbria.csv"
OCG_data="/Users/annasintsova/git_repos/HUTI-RNAseq/analysis/DE/data/processed_counts/2018-01-29_combined_counts.csv"

In [11]:
ocg = pd.read_csv(OCG_data, index_col = 'CFT073')
to_drop=[c for c in list(ocg.columns) if 'counts' in c or 'MG1655' in c or 'Unnamed' in c or 'seq' in c]
ocg = ocg.drop(to_drop, axis = 1)
ocg.head()

//anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (6,8,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,HM66,HM17,HM14,HM56,HM60,HM43,HM01,HM54,HM06,HM57,...,HM57_UR_RPKM,HM57_UTI_RPKM,HM60_UR_RPKM,HM60_UTI_RPKM,HM68_UR_RPKM,HM68_UTI_RPKM,HM66_UR_RPKM,HM66_UTI_RPKM,HM86_UR_RPKM,HM86_UTI_RPKM
CFT073,,,,,,,,,,,,,,,,,,,,,
c5491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c0002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c0006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c0008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c0009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
fimb= pd.read_csv(fimbriae_data, index_col='genome_locus_tag')
fimb.head()

                 gene_symbol fimbrial_type        function  genome
genome_locus_tag
c5391                   fimB        Type 1             NaN  CFT073
c5392                   fimE        Type 1             NaN  CFT073
c5393                   fimA        Type 1  main structure  CFT073
c5394                   fimI        Type 1             NaN  CFT073
c5395                   fimC        Type 1             NaN  CFT073

In [15]:
fim_ocg=fimb.merge(ocg, how='inner', left_index=True, right_index=True)

,gene_symbol,fimbrial_type,function,genome,HM66,HM17,HM14,HM56,HM60,HM43,...,HM57_UR_RPKM,HM57_UTI_RPKM,HM60_UR_RPKM,HM60_UTI_RPKM,HM68_UR_RPKM,HM68_UTI_RPKM,HM66_UR_RPKM,HM66_UTI_RPKM,HM86_UR_RPKM,HM86_UTI_RPKM
c0167,yadK,Yad,NaN,CFT073,PROKKA_03559,PROKKA_01704,PROKKA_04753,PROKKA_04581,PROKKA_03272,PROKKA_01413,...,6.10,0.05,2.53,0.13,14.51,0.10,5.76,0.00,1.79,1.26
c0168,yadL,Yad,NaN,CFT073,PROKKA_03560,PROKKA_01703,PROKKA_04754,PROKKA_04580,PROKKA_03271,PROKKA_01412,...,5.47,0.02,7.07,0.11,16.30,0.10,6.32,0.00,1.97,0.31
c0169,yadM,Yad,NaN,CFT073,PROKKA_03561,PROKKA_01702,PROKKA_04755,PROKKA_04579,NaN,PROKKA_01411,...,8.53,0.20,NaN,NaN,26.04,0.19,12.34,0.27,1.88,0.83
c0170,NaN,Yad,NaN,CFT073,NaN,PROKKA_01701,PROKKA_04756,PROKKA_04578,PROKKA_03269,NaN,...,2.81,0.11,2.81,0.09,6.51,0.14,NaN,NaN,2.88,1.23
c0171,NaN,Yad,NaN,CFT073,PROKKA_03564,PROKKA_01700,PROKKA_04757,PROKKA_04577,PROKKA_03267,PROKKA_01408,...,1.82,0.28,1.14,0.04,4.69,0.12,2.12,0.21,0.90,1.14

In [30]:
to_drop = [c for c in list(fim_ocg.columns) if 'RPKM' in c] + ['gene_symbol', 'function', 'genome', 'gene_symbol']
fim_pa=fim_ocg.drop(to_drop, axis = 1)
fim_type = fim_pa.pop("fimbrial_type")
fim_pa.fillna(0, inplace=True)
fim_pa.replace("PARALOGS", 2, inplace=True)
fim_pa.replace("PROKKA.*", 1, inplace=True, regex=True)
fim_pa.head()

,HM66,HM17,HM14,HM56,HM60,HM43,HM01,HM54,HM06,HM57,HM07,HM86,HM68,HM03
c0167,1,1,1,1,1,1,1,1,1,1,1,1,1,1
c0168,1,1,1,1,1,1,0,1,1,1,1,1,1,1
c0169,1,1,1,1,0,1,1,1,1,1,1,1,1,1
c0170,0,1,1,1,1,0,0,1,1,1,1,1,1,1
c0171,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
import seaborn as sns; sns.set(color_codes=True)
iris=sns.load_dataset("iris")
species=iris.pop("species")
species
g = sns.clustermap(fim_pa)